name: Development Build

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: [self-hosted]
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Check if /var/www/html/MakitaB2B is a git repository
        id: check_repo
        run: |
          if [ -d "/var/www/html/MakitaB2B/.git" ]; then
            echo "::set-output name=is_git_repo::true"
          else
            echo "::set-output name=is_git_repo::false"
          fi

      - name: Add /var/www/html/MakitaB2B as a safe Git directory
        run: |
          git config --global --add safe.directory /var/www/html/MakitaB2B

      - name: Clone repository if not a git repository
        if: steps.check_repo.outputs.is_git_repo == 'false'
        run: |
          sudo rm -rf /var/www/html/MakitaB2B
          sudo git clone https://github.com/MakitaB2B/MakitaB2B.git /var/www/html/MakitaB2B

      - name: Pull latest changes and install dependencies
        run: |
          cd /var/www/html/MakitaB2B
          sudo git clean -f -d
          sudo git stash
          sudo git pull origin development
          sudo composer install

      - name: Ensure storage and cache directories exist
        run: |
          sudo mkdir -p /var/www/html/MakitaB2B/storage
          sudo mkdir -p /var/www/html/MakitaB2B/bootstrap/cache

      - name: Set correct permissions for storage and cache
        run: |
          sudo chown -R www-data:www-data /var/www/html/MakitaB2B/storage /var/www/html/MakitaB2B/bootstrap/cache
          sudo chmod -R 775 /var/www/html/MakitaB2B/storage /var/www/html/MakitaB2B/bootstrap/cache

          # Additional permissions specific to Laravel
          sudo chown -R www-data:www-data /var/www/html/MakitaB2B/storage/*
          sudo chown -R www-data:www-data /var/www/html/MakitaB2B/bootstrap/cache/*

          # Ensure specific permissions for storage directories
          sudo chmod -R 777 /var/www/html/MakitaB2B/storage
          sudo chmod -R 777 /var/www/html/MakitaB2B/storage/framework
          sudo chmod -R 777 /var/www/html/MakitaB2B/storage/framework/sessions
          sudo chmod -R 777 /var/www/html/MakitaB2B/storage/logs
