name: Development Build

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: [self-hosted]
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Run Git Pull and Composer Install
        run: cd /var/www/healthapi && git clean -f -d && git stash && git pull origin development && composer install 
