name: Push-to-EC2

# Trigger deployment only on push to development branch
on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploy to EC2 on development branch push
    runs-on: ubuntu-latest

      - name: Deploy to EC2
        uses: MakitaB2B/MakitaB2B@development
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.DEVMAKITAB2BHOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
