name: Development Build

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: [self-hosted]
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Check if /var/www/html/MakitaB2B is a git repository
        id: check_repo
        run: |
          if [ -d "/var/www/html/MakitaB2B/.git" ]; then
            echo "::set-output name=is_git_repo::true"
          else
            echo "::set-output name=is_git_repo::false"
          fi

      - name: Clone repository if not a git repository
        if: steps.check_repo.outputs.is_git_repo == 'false'
        run: |
          sudo rm -rf /var/www/html
          sudo git clone https://github.com/MakitaB2B/MakitaB2B.git /var/www/html/MakitaB2B

      - name: Pull latest changes and install dependencies
        run: |
          cd /var/www/html/MakitaB2B
          sudo git clean -f -d
          sudo git stash
          sudo git pull origin development
          sudo composer install
